/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AureliaRouteImport } from './routes/aurelia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PathRouteImport } from './routes/path'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RitualsRouteImport } from './routes/rituals'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ApiAureliaRouteImport } from './routes/api/aurelia'
import { Route as ApiAureliaVoiceRouteImport } from './routes/api/aurelia-voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AureliaRoute = AureliaRouteImport.update({
  id: '/aurelia',
  path: '/aurelia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsRoute = RitualsRouteImport.update({
  id: '/rituals',
  path: '/rituals',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAureliaRoute = ApiAureliaRouteImport.update({
  id: '/api/aurelia',
  path: '/api/aurelia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAureliaVoiceRoute = ApiAureliaVoiceRouteImport.update({
  id: '/api/aurelia-voice',
  path: '/api/aurelia-voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aurelia': typeof AureliaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/rituals': typeof RitualsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/voice': typeof VoiceRoute
  '/api/aurelia': typeof ApiAureliaRoute
  '/api/aurelia-voice': typeof ApiAureliaVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aurelia': typeof AureliaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/rituals': typeof RitualsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/voice': typeof VoiceRoute
  '/api/aurelia': typeof ApiAureliaRoute
  '/api/aurelia-voice': typeof ApiAureliaVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aurelia': typeof AureliaRoute
  '/auth': typeof AuthRoute
  '/journal': typeof JournalRoute
  '/library': typeof LibraryRoute
  '/onboarding': typeof OnboardingRoute
  '/path': typeof PathRoute
  '/progress': typeof ProgressRoute
  '/rituals': typeof RitualsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/voice': typeof VoiceRoute
  '/api/aurelia': typeof ApiAureliaRoute
  '/api/aurelia-voice': typeof ApiAureliaVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aurelia'
    | '/auth'
    | '/journal'
    | '/library'
    | '/onboarding'
    | '/path'
    | '/progress'
    | '/rituals'
    | '/saved'
    | '/settings'
    | '/studio'
    | '/voice'
    | '/api/aurelia'
    | '/api/aurelia-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aurelia'
    | '/auth'
    | '/journal'
    | '/library'
    | '/onboarding'
    | '/path'
    | '/progress'
    | '/rituals'
    | '/saved'
    | '/settings'
    | '/studio'
    | '/voice'
    | '/api/aurelia'
    | '/api/aurelia-voice'
  id:
    | '__root__'
    | '/'
    | '/aurelia'
    | '/auth'
    | '/journal'
    | '/library'
    | '/onboarding'
    | '/path'
    | '/progress'
    | '/rituals'
    | '/saved'
    | '/settings'
    | '/studio'
    | '/voice'
    | '/api/aurelia'
    | '/api/aurelia-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AureliaRoute: typeof AureliaRoute
  AuthRoute: typeof AuthRoute
  JournalRoute: typeof JournalRoute
  LibraryRoute: typeof LibraryRoute
  OnboardingRoute: typeof OnboardingRoute
  PathRoute: typeof PathRoute
  ProgressRoute: typeof ProgressRoute
  RitualsRoute: typeof RitualsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  VoiceRoute: typeof VoiceRoute
  ApiAureliaRoute: typeof ApiAureliaRoute
  ApiAureliaVoiceRoute: typeof ApiAureliaVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aurelia': {
      id: '/aurelia'
      path: '/aurelia'
      fullPath: '/aurelia'
      preLoaderRoute: typeof AureliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals': {
      id: '/rituals'
      path: '/rituals'
      fullPath: '/rituals'
      preLoaderRoute: typeof RitualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aurelia': {
      id: '/api/aurelia'
      path: '/api/aurelia'
      fullPath: '/api/aurelia'
      preLoaderRoute: typeof ApiAureliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/aurelia-voice': {
      id: '/api/aurelia-voice'
      path: '/api/aurelia-voice'
      fullPath: '/api/aurelia-voice'
      preLoaderRoute: typeof ApiAureliaVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AureliaRoute: AureliaRoute,
  AuthRoute: AuthRoute,
  JournalRoute: JournalRoute,
  LibraryRoute: LibraryRoute,
  OnboardingRoute: OnboardingRoute,
  PathRoute: PathRoute,
  ProgressRoute: ProgressRoute,
  RitualsRoute: RitualsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  VoiceRoute: VoiceRoute,
  ApiAureliaRoute: ApiAureliaRoute,
  ApiAureliaVoiceRoute: ApiAureliaVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
